name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Change the version as per your project
          extensions: mbstring, intl, pdo_mysql
          coverage: none
          tools: composer

      # Install dependencies
      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      # Run PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G

      # Run PHPCS
      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=PSR12 src/

      # Run PHPUnit
      - name: Run PHPUnit
        env:
          APP_ENV: test
          DATABASE_URL: 'sqlite:///:memory:'
        run: vendor/bin/phpunit --testdox
